// --- Directions
// Print out the n-th entry in the fibonacci series.
// The fibonacci series is an ordering of numbers where
// each number is the sum of the preceeding two.
// For example, the sequence
//  [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
// forms the first ten entries of the fibonacci series.
// Example:
//   fib(4) === 3


// Iterative Solution:
// Create an array and assemble all the numbers up to entry 'n'
// Return it
// The trick here is to recognize that the first 2 numbers 0 and 1 can't be generated by the FOR loop
// because there are no numbers that come before 0 and 1 so we need to place them in teh array when creating a variable

// Runtime Complexity - Linear because for every increase in 'n' we need
// to do one more calculation which will never change


function fib(n) {

    const result = [0, 1];

    // Creating a FOR loop that will start at i = 2 because we already have [0, 1] array
    for (let i = 2; i <= n; i++) {
        // Pulling out the previous 2 records
        const a = result[i - 1];
        const b = result[i - 2];

        result.push(a + b);
    }

    return result[n];
}
